#!/bin/sh
set -eu
mkdir -p build
cd build
cmake ..
make -j$(nproc)
mkdir -p AppDir/usr/lib
make DESTDIR=AppDir/ install
cp ../sys/steam-static-shortcuts.png AppDir
cp ../sys/steam-static-shortcuts.desktop AppDir
cp ../sys/AppRun AppDir
cp -r ../sys/share AppDir/usr
cp $(dirname $(gcc --print-file-name=libgcc_s.so))/libgcc_s* AppDir/usr/lib
cp $(dirname $(gcc --print-file-name=libstdc++.so))/libstdc++* AppDir/usr/lib
cp $(dirname $(gcc --print-file-name=libyaml-cpp.so))/libyaml-cpp* AppDir/usr/lib
ARCH=x86_64 appimagetool -n AppDir SteamStaticShortcuts.AppImage
